apiVersion: v1
kind: Service
metadata:
  name: my-demo-app
  namespace: default
spec:
  ports:
  - name: http1
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-demo-app
    version: '63ee854'
  sessionAffinity: None
  type: LoadBalancer
